# Generated by Django 4.2.6 on 2023-11-25 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("flavor", models.CharField(max_length=100)),
                ("icing", models.TextField()),
                ("filling", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("image", models.URLField()),
                ("inventory", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
