# Generated by Django 4.2.6 on 2023-11-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
