# Generated by Django 4.2.6 on 2023-11-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0002_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
