# Generated by Django 4.2.6 on 2023-10-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_cupcake_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cupcake",
            name="nome",
            field=models.CharField(default="cupcake", max_length=100),
            preserve_default=False,
        ),
    ]
