# Generated by Django 4.2.6 on 2023-11-03 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_endereco_bairro_alter_endereco_cep_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="id",
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
