# Generated by Django 4.2.6 on 2023-11-03 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_pedido_id_alter_pedido_numero_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="data",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
