# Generated by Django 4.2.6 on 2023-11-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_pedido_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
