# Generated by Django 4.2.6 on 2023-11-05 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_usuario_email"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="ItemPedido",
        ),
    ]
