# Generated by Django 4.2.6 on 2023-11-05 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_rename_item_itempedido"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itempedido",
            old_name="produto",
            new_name="cupcake",
        ),
    ]
