# Generated by Django 4.2.6 on 2023-11-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_rename_produto_itempedido_cupcake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
