# Generated by Django 4.2.6 on 2023-11-05 20:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_alter_usuario_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="itens",
        ),
        migrations.AddField(
            model_name="itempedido",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=(1, 0), max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itempedido",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2, default=django.utils.timezone.now, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="app.pedido",
            ),
        ),
    ]
