# Generated by Django 4.2.6 on 2023-12-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "Já existe uma conta cadastrada com este email "
                },
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
